project_id = "svmgrwciiftpopvqjbxz"

[functions.create-pix-payment]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-reminder]
verify_jwt = false

[functions.generate-pix]
verify_jwt = false
